spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/timerService

logging:
  level:
    root: info
    com.ank.timer: debug
    org:
      springframework:
        web:
          client: trace

timer-scheduler:
  thread-pool:
    core-size: 5
    max-size: 5
  cron: "*/1 * * * * *"
